2022-02-15 19:45:36,461 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 19:46:31,001 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 20:15:53,350 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 22:27:54,502 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 22:30:14,912 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 22:35:32,551 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-15 22:36:03,259 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-16 22:09:07,231 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-16 22:09:52,650 ERROR: Exception on /reset_password_request [POST] [in e:\git\py_blog2\venv\lib\site-packages\flask\app.py:1458]
Traceback (most recent call last):
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\git\py_blog2\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "E:\git\py_blog2\app\email.py", line 18, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\git\py_blog2\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2022-02-16 22:11:36,754 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-16 22:11:46,845 ERROR: Exception on /reset_password_request [POST] [in e:\git\py_blog2\venv\lib\site-packages\flask\app.py:1458]
Traceback (most recent call last):
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\git\py_blog2\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\git\py_blog2\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
  File "E:\git\py_blog2\app\email.py", line 18, in send_password_reset_email
    token = user.get_reset_password_token()
  File "E:\git\py_blog2\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2022-02-16 22:13:04,472 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-16 22:17:38,864 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:47]
2022-02-17 07:41:06,794 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:49]
2022-02-17 07:52:45,488 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:51]
2022-02-18 07:56:52,607 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:52]
2022-02-18 08:08:51,474 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:52]
2022-02-18 08:09:04,754 INFO: Microblog startup [in E:\git\py_blog2\app\__init__.py:52]
